// Cosmos DB scaffolding (lazy). Real client initialization to be added when endpoint & key / MSI ready.
export interface UserProfileDoc {
  id: string; // userId
  email: string;
  name?: string;
  roles?: string[];
  createdAt: string;
  updatedAt: string;
}

export interface UserProgressDoc {
  id: string; // composite or autogenerated
  userId: string;
  courseId: string;
  lessonId: string;
  completedAt: string;
}

// Repository interfaces (implementation pending once @azure/cosmos is added)
export interface UserRepository {
  get(userId: string): Promise<UserProfileDoc | null>;
  upsert(doc: UserProfileDoc): Promise<void>;
}

export interface ProgressRepository {
  recordProgress(ev: Omit<UserProgressDoc, 'id'>): Promise<void>;
  listForCourse(userId: string, courseId: string): Promise<UserProgressDoc[]>;
}

// Temporary no-op factories to be replaced.
export function createUserRepository(): UserRepository {
  return {
    async get() { return null; },
    async upsert() { /* noop */ }
  };
}

export function createProgressRepository(): ProgressRepository {
  return {
    async recordProgress() { /* noop */ },
    async listForCourse() { return []; }
  };
}
