#!/bin/bash
#
# ThinkForward Automated Deployment Script
# This script automates the deployment process to Azure with proper NextAuth configuration
#

set -e # Exit on any error

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Banner
echo -e "${BLUE}========================================================${NC}"
echo -e "${BLUE}       ThinkForward Automated Deployment Script         ${NC}"
echo -e "${BLUE}========================================================${NC}"
echo ""

# Check if running in project root directory
if [ ! -f "./package.json" ]; then
  if [ -f "./thinkForward/package.json" ]; then
    cd ./thinkForward
    echo -e "${YELLOW}Moved to thinkForward directory${NC}"
  else
    echo -e "${RED}Error: Please run this script from the project root directory${NC}"
    exit 1
  fi
fi

# Default values
AZURE_WEBAPP_NAME=""
RESOURCE_GROUP=""
SKIP_NEXTAUTH_CHECK=false
SKIP_BUILD=false
SKIP_DEPLOY=false

# Display the help menu
show_help() {
  echo "Usage: $0 [options]"
  echo ""
  echo "Options:"
  echo "  -h, --help                   Show this help menu"
  echo "  -g, --resource-group NAME    Azure resource group name"
  echo "  -w, --webapp NAME            Azure Web App name"
  echo "  --skip-nextauth-check        Skip NextAuth secret verification"
  echo "  --skip-build                 Skip the build process"
  echo "  --skip-deploy                Skip the deployment (useful for testing)"
  echo ""
  echo "Examples:"
  echo "  $0 -w mywebapp                       # Deploy to 'mywebapp'"
  echo "  $0 -w mywebapp -g myresourcegroup    # Specify both webapp and resource group"
  echo "  $0 -w mywebapp --skip-build          # Skip the build process"
  echo ""
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -h|--help)
      show_help
      exit 0
      ;;
    -g|--resource-group)
      RESOURCE_GROUP="$2"
      shift
      shift
      ;;
    -w|--webapp)
      AZURE_WEBAPP_NAME="$2"
      shift
      shift
      ;;
    --skip-nextauth-check)
      SKIP_NEXTAUTH_CHECK=true
      shift
      ;;
    --skip-build)
      SKIP_BUILD=true
      shift
      ;;
    --skip-deploy)
      SKIP_DEPLOY=true
      shift
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      show_help
      exit 1
      ;;
  esac
done

# Check if webapp name is provided
if [ -z "$AZURE_WEBAPP_NAME" ]; then
  echo -e "${RED}Error: Azure webapp name is required${NC}"
  echo -e "${YELLOW}Use -w or --webapp option to specify the webapp name${NC}"
  exit 1
fi

# If resource group is not provided, try to find it
if [ -z "$RESOURCE_GROUP" ]; then
  echo -e "${YELLOW}Resource group not specified, trying to determine automatically...${NC}"
  RESOURCE_GROUP=$(az webapp list --query "[?name=='$AZURE_WEBAPP_NAME'].resourceGroup" -o tsv)
  
  if [ -z "$RESOURCE_GROUP" ]; then
    echo -e "${RED}Could not determine resource group for webapp $AZURE_WEBAPP_NAME${NC}"
    echo -e "${RED}Please provide the resource group using the -g option${NC}"
    exit 1
  else
    echo -e "${GREEN}Found resource group: $RESOURCE_GROUP${NC}"
  fi
fi

# Check NextAuth secret if not skipped
if [ "$SKIP_NEXTAUTH_CHECK" = false ]; then
  echo -e "${BLUE}Checking NextAuth configuration...${NC}"
  
  # Check if .env.production exists
  if [ ! -f ".env.production" ]; then
    echo -e "${YELLOW}Warning: .env.production file not found${NC}"
    
    # Check if we have a template to copy
    if [ -f ".env.production.template" ]; then
      echo -e "${YELLOW}Creating .env.production from template...${NC}"
      cp ".env.production.template" ".env.production"
    else
      echo -e "${YELLOW}Creating basic .env.production file...${NC}"
      echo "# Generated by deployment script" > ".env.production"
      echo "NODE_ENV=production" >> ".env.production"
      echo "NEXTAUTH_URL=https://$AZURE_WEBAPP_NAME.azurewebsites.net" >> ".env.production"
    fi
  fi
  
  # Check if NEXTAUTH_SECRET is set in .env.production
  if ! grep -q "^NEXTAUTH_SECRET=" ".env.production"; then
    echo -e "${YELLOW}NEXTAUTH_SECRET not found in .env.production${NC}"
    
    # Try to find it in other env files
    SECRET=""
    for file in ".env.local" ".env"; do
      if [ -f "$file" ] && grep -q "^NEXTAUTH_SECRET=" "$file"; then
        SECRET=$(grep "^NEXTAUTH_SECRET=" "$file" | cut -d'=' -f2)
        echo -e "${GREEN}Found NEXTAUTH_SECRET in $file${NC}"
        break
      fi
    done
    
    # If not found, generate a new one
    if [ -z "$SECRET" ]; then
      SECRET=$(openssl rand -hex 32)
      echo -e "${YELLOW}Generated new NEXTAUTH_SECRET${NC}"
    fi
    
    # Add it to .env.production
    echo "NEXTAUTH_SECRET=$SECRET" >> ".env.production"
    echo -e "${GREEN}Added NEXTAUTH_SECRET to .env.production${NC}"
  else
    echo -e "${GREEN}NEXTAUTH_SECRET found in .env.production${NC}"
  fi
  
  # Ensure NEXTAUTH_URL is set correctly
  if ! grep -q "^NEXTAUTH_URL=" ".env.production" || ! grep -q "^NEXTAUTH_URL=https://$AZURE_WEBAPP_NAME.azurewebsites.net" ".env.production"; then
    echo -e "${YELLOW}Setting correct NEXTAUTH_URL in .env.production...${NC}"
    # If NEXTAUTH_URL exists, replace it, otherwise add it
    if grep -q "^NEXTAUTH_URL=" ".env.production"; then
      sed -i.bak "s|^NEXTAUTH_URL=.*$|NEXTAUTH_URL=https://$AZURE_WEBAPP_NAME.azurewebsites.net|" ".env.production"
      rm -f ".env.production.bak"
    else
      echo "NEXTAUTH_URL=https://$AZURE_WEBAPP_NAME.azurewebsites.net" >> ".env.production"
    fi
  fi
  
  # Extract the secret from .env.production for Azure config
  NEXTAUTH_SECRET=$(grep "^NEXTAUTH_SECRET=" ".env.production" | cut -d'=' -f2)
  
  # Update Azure app settings
  echo -e "${BLUE}Updating Azure App Service settings...${NC}"
  az webapp config appsettings set \
    --name "$AZURE_WEBAPP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --settings "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" "NEXTAUTH_URL=https://$AZURE_WEBAPP_NAME.azurewebsites.net" \
    --output table
fi

# Build the application if not skipped
if [ "$SKIP_BUILD" = false ]; then
  echo -e "${BLUE}Building the application...${NC}"
  
  # Install dependencies if node_modules doesn't exist
  if [ ! -d "node_modules" ] || [ "$(find node_modules -maxdepth 0 -empty)" ]; then
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm install
  fi
  
  # Build the app
  echo -e "${YELLOW}Running production build...${NC}"
  npm run build
  
  if [ $? -ne 0 ]; then
    echo -e "${RED}Build failed${NC}"
    exit 1
  else
    echo -e "${GREEN}Build successful${NC}"
  fi
else
  echo -e "${YELLOW}Skipping build process${NC}"
fi

# Deploy to Azure if not skipped
if [ "$SKIP_DEPLOY" = false ]; then
  echo -e "${BLUE}Deploying to Azure...${NC}"
  
  # Check if we have a deployment profile
  PROFILE_XML="thinkforward-publish-profile.xml"
  if [ ! -f "$PROFILE_XML" ]; then
    echo -e "${YELLOW}Publish profile not found. Downloading from Azure...${NC}"
    az webapp deployment list-publishing-profiles \
      --name "$AZURE_WEBAPP_NAME" \
      --resource-group "$RESOURCE_GROUP" \
      --xml > "$PROFILE_XML"
      
    if [ $? -ne 0 ]; then
      echo -e "${RED}Failed to download publish profile${NC}"
      echo -e "${YELLOW}Make sure you are logged in to Azure CLI and have permissions${NC}"
      exit 1
    fi
  fi
  
  # Deploy using the azure-webapps CLI
  echo -e "${YELLOW}Deploying to $AZURE_WEBAPP_NAME...${NC}"
  
  # Create zip file of the build
  echo -e "${YELLOW}Creating deployment package...${NC}"
  ZIP_FILE="deployment-$(date +%Y%m%d%H%M%S).zip"
  
  # Different zip commands for different platforms
  if command -v zip &> /dev/null; then
    # Use zip command if available
    zip -r "$ZIP_FILE" .next node_modules public package.json next.config.mjs .env.production server.js -x "**/.git/**" -x "**/node_modules/.cache/**"
  elif command -v 7z &> /dev/null; then
    # Use 7z if available
    7z a -r "$ZIP_FILE" .next node_modules public package.json next.config.mjs .env.production server.js -xr!.git -xr!node_modules/.cache
  else
    echo -e "${RED}Error: No zip utility found (zip or 7z)${NC}"
    exit 1
  fi
  
  # Deploy the zip file
  echo -e "${YELLOW}Uploading and deploying package...${NC}"
  az webapp deployment source config-zip \
    --resource-group "$RESOURCE_GROUP" \
    --name "$AZURE_WEBAPP_NAME" \
    --src "$ZIP_FILE"
  
  if [ $? -ne 0 ]; then
    echo -e "${RED}Deployment failed${NC}"
    exit 1
  else
    echo -e "${GREEN}Deployment successful${NC}"
    # Clean up zip file
    rm "$ZIP_FILE"
  fi
  
  # Restart the web app
  echo -e "${BLUE}Restarting the web app...${NC}"
  az webapp restart \
    --name "$AZURE_WEBAPP_NAME" \
    --resource-group "$RESOURCE_GROUP"
  
  if [ $? -ne 0 ]; then
    echo -e "${YELLOW}Warning: Failed to restart the web app${NC}"
  else
    echo -e "${GREEN}Web app restarted${NC}"
  fi
  
  # Open the deployed app in browser
  echo -e "${BLUE}Opening the deployed app in browser...${NC}"
  open "https://$AZURE_WEBAPP_NAME.azurewebsites.net"
else
  echo -e "${YELLOW}Skipping deployment${NC}"
fi

echo ""
echo -e "${BLUE}========================================================${NC}"
echo -e "${GREEN}Deployment process completed${NC}"
echo -e "${BLUE}========================================================${NC}"

exit 0