#!/bin/bash
#
# ThinkForward NextAuth Automation Script
# This script automates the NextAuth configuration process for both local and Azure environments
#

set -e # Exit on any error

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Banner
echo -e "${BLUE}========================================================${NC}"
echo -e "${BLUE}       ThinkForward NextAuth Automation Script          ${NC}"
echo -e "${BLUE}========================================================${NC}"
echo ""

# Check if running in project root directory
if [ ! -f "./package.json" ]; then
  if [ -f "./thinkForward/package.json" ]; then
    cd ./thinkForward
    echo -e "${YELLOW}Moved to thinkForward directory${NC}"
  else
    echo -e "${RED}Error: Please run this script from the project root directory${NC}"
    exit 1
  fi
fi

# Default values
NEXTAUTH_SECRET_FILE=".env.local"
AZURE_WEBAPP_NAME=""
RESOURCE_GROUP=""

# Function to generate a secure random string for NEXTAUTH_SECRET
generate_nextauth_secret() {
  echo $(openssl rand -hex 32)
}

# Function to extract existing NEXTAUTH_SECRET from .env files
extract_nextauth_secret() {
  local file=$1
  if [ -f "$file" ]; then
    secret=$(grep "^NEXTAUTH_SECRET=" "$file" | cut -d'=' -f2)
    if [ ! -z "$secret" ]; then
      echo "$secret"
      return 0
    fi
  fi
  return 1
}

# Function to update .env files with NEXTAUTH_SECRET
update_env_file() {
  local file=$1
  local secret=$2
  
  if [ -f "$file" ]; then
    # If NEXTAUTH_SECRET already exists, replace it
    if grep -q "^NEXTAUTH_SECRET=" "$file"; then
      sed -i.bak "s/^NEXTAUTH_SECRET=.*$/NEXTAUTH_SECRET=$secret/" "$file"
      rm -f "${file}.bak"
      echo -e "${GREEN}Updated NEXTAUTH_SECRET in $file${NC}"
    else
      # Otherwise, append it
      echo "" >> "$file"
      echo "# Added by NextAuth automation script" >> "$file"
      echo "NEXTAUTH_SECRET=$secret" >> "$file"
      echo -e "${GREEN}Added NEXTAUTH_SECRET to $file${NC}"
    fi
  else
    echo -e "${YELLOW}Creating new $file file with NEXTAUTH_SECRET${NC}"
    echo "# Generated by NextAuth automation script" > "$file"
    echo "NEXTAUTH_SECRET=$secret" >> "$file"
  fi
}

# Check if Azure CLI is installed
check_azure_cli() {
  if ! command -v az &> /dev/null; then
    echo -e "${RED}Azure CLI is not installed. Please install it first:${NC}"
    echo -e "${YELLOW}https://docs.microsoft.com/en-us/cli/azure/install-azure-cli${NC}"
    return 1
  fi
  
  # Check if logged in
  az account show &> /dev/null
  if [ $? -ne 0 ]; then
    echo -e "${YELLOW}You're not logged into Azure. Please log in:${NC}"
    az login
    if [ $? -ne 0 ]; then
      echo -e "${RED}Failed to log in to Azure${NC}"
      return 1
    fi
  fi
  
  return 0
}

# Function to update Azure App Service settings
update_azure_settings() {
  local webapp=$1
  local resource_group=$2
  local secret=$3
  
  echo -e "${BLUE}Updating Azure App Service settings...${NC}"
  
  # If resource group is not provided, try to find it
  if [ -z "$resource_group" ]; then
    echo -e "${YELLOW}Resource group not specified, trying to determine automatically...${NC}"
    resource_group=$(az webapp list --query "[?name=='$webapp'].resourceGroup" -o tsv)
    
    if [ -z "$resource_group" ]; then
      echo -e "${RED}Could not determine resource group for webapp $webapp${NC}"
      echo -e "${RED}Please provide the resource group using the -g option${NC}"
      return 1
    else
      echo -e "${GREEN}Found resource group: $resource_group${NC}"
    fi
  fi
  
  # Update the app settings
  echo -e "${YELLOW}Setting NEXTAUTH_SECRET for $webapp in $resource_group...${NC}"
  az webapp config appsettings set \
    --name "$webapp" \
    --resource-group "$resource_group" \
    --settings "NEXTAUTH_SECRET=$secret" \
    --output table
  
  # Verify that the setting was applied
  echo -e "${BLUE}Verifying NEXTAUTH_SECRET was set...${NC}"
  result=$(az webapp config appsettings list \
    --name "$webapp" \
    --resource-group "$resource_group" \
    --query "[?name=='NEXTAUTH_SECRET'].value" -o tsv)
  
  if [ ! -z "$result" ]; then
    echo -e "${GREEN}NEXTAUTH_SECRET successfully set in Azure App Service${NC}"
    echo -e "${YELLOW}Note: The exact value is masked for security reasons${NC}"
    return 0
  else
    echo -e "${RED}Failed to set NEXTAUTH_SECRET in Azure App Service${NC}"
    return 1
  fi
}

# Display the help menu
show_help() {
  echo "Usage: $0 [options]"
  echo ""
  echo "Options:"
  echo "  -h, --help                   Show this help menu"
  echo "  -g, --resource-group NAME    Azure resource group name"
  echo "  -w, --webapp NAME            Azure Web App name"
  echo "  -s, --secret SECRET          Use specific NextAuth secret (if not provided, will be extracted or generated)"
  echo "  -l, --local-only             Update only local environment files (skip Azure)"
  echo "  -a, --azure-only             Update only Azure settings (skip local files)"
  echo "  --env-file PATH              Path to .env file to use/create (default: .env.local)"
  echo ""
  echo "Examples:"
  echo "  $0 -w mywebapp                       # Update local files and Azure webapp 'mywebapp'"
  echo "  $0 -w mywebapp -g myresourcegroup    # Specify both webapp and resource group"
  echo "  $0 -l                                # Update only local files"
  echo "  $0 -a -w mywebapp                    # Update only Azure webapp 'mywebapp'"
  echo "  $0 --env-file .env.production        # Use .env.production instead of .env.local"
  echo ""
}

# Parse command line arguments
LOCAL_ONLY=false
AZURE_ONLY=false
NEXTAUTH_SECRET=""

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    -h|--help)
      show_help
      exit 0
      ;;
    -g|--resource-group)
      RESOURCE_GROUP="$2"
      shift
      shift
      ;;
    -w|--webapp)
      AZURE_WEBAPP_NAME="$2"
      shift
      shift
      ;;
    -s|--secret)
      NEXTAUTH_SECRET="$2"
      shift
      shift
      ;;
    -l|--local-only)
      LOCAL_ONLY=true
      shift
      ;;
    -a|--azure-only)
      AZURE_ONLY=true
      shift
      ;;
    --env-file)
      NEXTAUTH_SECRET_FILE="$2"
      shift
      shift
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      show_help
      exit 1
      ;;
  esac
done

# Get or generate NEXTAUTH_SECRET
if [ -z "$NEXTAUTH_SECRET" ]; then
  # Try to extract from env files
  for file in ".env.local" ".env.production" ".env"; do
    if extract_nextauth_secret "$file" > /dev/null; then
      NEXTAUTH_SECRET=$(extract_nextauth_secret "$file")
      echo -e "${GREEN}Using existing NEXTAUTH_SECRET from $file${NC}"
      break
    fi
  done
  
  # If still empty, generate a new one
  if [ -z "$NEXTAUTH_SECRET" ]; then
    NEXTAUTH_SECRET=$(generate_nextauth_secret)
    echo -e "${YELLOW}Generated new NEXTAUTH_SECRET${NC}"
  fi
else
  echo -e "${BLUE}Using provided NEXTAUTH_SECRET${NC}"
fi

# Update local files if not Azure-only
if [ "$AZURE_ONLY" = false ]; then
  echo -e "${BLUE}Updating local environment files...${NC}"
  
  # Update primary env file
  update_env_file "$NEXTAUTH_SECRET_FILE" "$NEXTAUTH_SECRET"
  
  # Also update .env.production if it exists or if .env.production.template exists
  if [ -f ".env.production" ] || [ -f ".env.production.template" ]; then
    if [ ! -f ".env.production" ] && [ -f ".env.production.template" ]; then
      cp ".env.production.template" ".env.production"
      echo -e "${YELLOW}Created .env.production from template${NC}"
    fi
    update_env_file ".env.production" "$NEXTAUTH_SECRET"
  fi
  
  echo -e "${GREEN}Local environment files updated successfully${NC}"
fi

# Update Azure settings if not local-only and webapp name is provided
if [ "$LOCAL_ONLY" = false ] && [ ! -z "$AZURE_WEBAPP_NAME" ]; then
  if check_azure_cli; then
    update_azure_settings "$AZURE_WEBAPP_NAME" "$RESOURCE_GROUP" "$NEXTAUTH_SECRET"
  else
    echo -e "${RED}Skipping Azure update due to CLI issues${NC}"
  fi
elif [ "$LOCAL_ONLY" = false ] && [ -z "$AZURE_WEBAPP_NAME" ] && [ "$AZURE_ONLY" = true ]; then
  echo -e "${RED}Error: Azure webapp name is required for Azure updates${NC}"
  echo -e "${YELLOW}Use -w or --webapp option to specify the webapp name${NC}"
  exit 1
fi

echo ""
echo -e "${BLUE}========================================================${NC}"
echo -e "${GREEN}NextAuth setup completed${NC}"
echo ""
if [ "$LOCAL_ONLY" = false ] && [ ! -z "$AZURE_WEBAPP_NAME" ]; then
  echo -e "${YELLOW}Remember to restart your Azure App Service for the changes to take effect:${NC}"
  echo -e "${BLUE}az webapp restart --name $AZURE_WEBAPP_NAME --resource-group $RESOURCE_GROUP${NC}"
fi
echo -e "${BLUE}========================================================${NC}"

exit 0