#!/bin/bash
# Script to set up Azure resources in environment for local development

# Create azure-resources.env file if it doesn't exist
if [ ! -f ./azure-resources.env ]; then
  echo "Creating azure-resources.env file with placeholder values..."
  
  cat > ./azure-resources.env << EOL
# Azure Resources Configuration - Generated by setup-azure-local.sh
COSMOS_ENDPOINT=https://example.cosmos.azure.com:443/
COSMOS_KEY=placeholder-cosmos-key
COSMOS_DATABASE=thinkforward
AZURE_AD_CLIENT_ID=placeholder-client-id
AZURE_AD_CLIENT_SECRET=placeholder-client-secret
AZURE_AD_TENANT_ID=common
KEY_VAULT_URI=https://example.vault.azure.net/
STORAGE_ACCOUNT_NAME=placeholderstorage
STORAGE_ACCOUNT_KEY=placeholder-storage-key
APP_INSIGHTS_CONNECTION_STRING=InstrumentationKey=placeholder-key
EOL

  echo "Created azure-resources.env with placeholder values."
  echo "Update with real values before deploying to production."
fi

# Source the azure-resources.env file
source ./azure-resources.env

# Check for required variables and use fallbacks if needed
COSMOS_ENDPOINT=${COSMOS_ENDPOINT:-"https://example.cosmos.azure.com:443/"}
COSMOS_KEY=${COSMOS_KEY:-"placeholder-cosmos-key"}
COSMOS_DATABASE=${COSMOS_DATABASE:-"thinkforward"}
KEY_VAULT_URI=${KEY_VAULT_URI:-"https://example.vault.azure.net/"}

echo "Setting up Azure resources for local development..."

# Generate a random secret if NEXTAUTH_SECRET is not set
NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-$(openssl rand -hex 32)}

# Create .env.local file for development with Azure resources
cat > .env.local << EOL
# Azure Resources Configuration - Generated by setup-azure-local.sh

# Azure AD Authentication
AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID:-placeholder-client-id}
AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET:-placeholder-client-secret}
AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID:-common}

# NextAuth Configuration
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Cosmos DB Configuration
COSMOS_ENDPOINT="${COSMOS_ENDPOINT}"
COSMOS_KEY="${COSMOS_KEY}"
COSMOS_DATABASE="${COSMOS_DATABASE}"

# Key Vault Configuration
KEY_VAULT_URL="${KEY_VAULT_URI}"

# Blob Storage Configuration
STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME:-placeholder-storage-account}
STORAGE_ACCOUNT_KEY=${STORAGE_ACCOUNT_KEY:-placeholder-storage-key}
STORAGE_CONTAINER_NAME="content"

# Application Insights
APPLICATIONINSIGHTS_CONNECTION_STRING="${APP_INSIGHTS_CONNECTION_STRING:-InstrumentationKey=placeholder-key}"
APPLICATIONINSIGHTS_ROLE_NAME="thinkforward-web-local"

# Database URL for Prisma (fallback)
DATABASE_URL="file:./dev.db"
EOL

echo "Created .env.local file with Azure resources configuration."

# Check if we're using placeholder values and notify user
if [[ "$COSMOS_ENDPOINT" == *"example"* ]] || [[ "$COSMOS_KEY" == "placeholder"* ]]; then
  echo ""
  echo "⚠️  NOTICE: Using placeholder values for Cosmos DB."
  echo "The application will run with in-memory storage fallbacks."
  echo "User data will not persist between application restarts."
  echo ""
  echo "To use real Azure services:"
  echo "1. Update azure-resources.env with actual Azure resource values"
  echo "2. Run this script again"
else
  echo "Azure resources are configured with actual values."
fi

echo "Setup complete! You can now run the application locally."