#!/bin/bash
# Script to set up Azure resources in environment for local development

# Source the azure-resources.env file
source ./azure-resources.env

# Basic validation
if [[ -z "$COSMOS_DB_ENDPOINT" || -z "$COSMOS_DB_KEY" || -z "$KEY_VAULT_URI" ]]; then
  echo "Error: Required Azure resource values are missing. Check azure-resources.env file."
  exit 1
fi

# Create .env.local file for development with Azure resources
cat > .env.local << EOL
# Azure Resources Configuration - Generated by setup-azure-local.sh

# Azure AD Authentication
AZURE_AD_CLIENT_ID=${AZURE_AD_CLIENT_ID:-your-client-id}
AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET:-your-client-secret}
AZURE_AD_TENANT_ID=${AZURE_AD_TENANT_ID:-your-tenant-id}

# NextAuth Configuration
NEXTAUTH_URL=http://localhost:3006
NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-$(openssl rand -hex 32)}

# Cosmos DB Configuration
COSMOS_DB_ENDPOINT="${COSMOS_DB_ENDPOINT}"
COSMOS_DB_KEY="${COSMOS_DB_KEY}"
COSMOS_DB_DATABASE_ID="thinkforward"
COSMOS_DB_CONTAINER_ID="users"

# Key Vault Configuration
KEY_VAULT_URL="${KEY_VAULT_URI}"

# Blob Storage Configuration
STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME:-your-storage-account}
STORAGE_ACCOUNT_KEY=${STORAGE_ACCOUNT_KEY:-your-storage-key}
STORAGE_CONTAINER_NAME="content"

# Application Insights
APPLICATIONINSIGHTS_CONNECTION_STRING="${APP_INSIGHTS_CONNECTION_STRING:-InstrumentationKey=your-instrumentation-key}"
APPLICATIONINSIGHTS_ROLE_NAME="thinkforward-web-local"

# Database URL for Prisma (fallback)
DATABASE_URL="file:./dev.db"
EOL

echo "Created .env.local file with Azure resources configuration."
echo "Check and update any missing values before running the application."