#!/bin/bash
# standardize-env-vars.sh
# This script standardizes environment variable names for Azure deployment

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print header
echo -e "${BLUE}=== Standardizing Environment Variables for Azure Deployment ===${NC}"

# Check for .env files in priority order
ENV_FILES=(".env.local" ".env.development" ".env.production" ".env" "azure-resources.env")
ENV_FILE=""

for file in "${ENV_FILES[@]}"; do
  if [[ -f "$file" ]]; then
    ENV_FILE=$file
    echo -e "${GREEN}Found environment file: $ENV_FILE${NC}"
    break
  fi
done

if [[ -z "$ENV_FILE" ]]; then
  echo -e "${RED}No environment file found. Please create a .env.local file.${NC}"
  exit 1
fi

# Create/update .env.azure file for Azure deployment
echo -e "${BLUE}Creating .env.azure file for deployment...${NC}"

# Start with a clean file
> .env.azure

# Process variables from the found env file
echo "# Generated by standardize-env-vars.sh for Azure deployment" >> .env.azure
echo "# Created on $(date)" >> .env.azure
echo "" >> .env.azure

# Handle Cosmos DB variables
echo -e "${YELLOW}Standardizing Cosmos DB variables...${NC}"

# Check for COSMOS_ENDPOINT or COSMOS_DB_ENDPOINT
COSMOS_ENDPOINT=""
if grep -q "COSMOS_ENDPOINT" "$ENV_FILE"; then
  COSMOS_ENDPOINT=$(grep "COSMOS_ENDPOINT" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_ENDPOINT in $ENV_FILE${NC}"
elif grep -q "COSMOS_DB_ENDPOINT" "$ENV_FILE"; then
  COSMOS_ENDPOINT=$(grep "COSMOS_DB_ENDPOINT" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_DB_ENDPOINT in $ENV_FILE${NC}"
else
  echo -e "${RED}No Cosmos DB endpoint found in $ENV_FILE${NC}"
  echo -e "${YELLOW}Using placeholder value. Please update before deployment.${NC}"
  COSMOS_ENDPOINT="https://placeholder.documents.azure.com:443/"
fi

# Add standardized COSMOS variables to .env.azure
echo "# Cosmos DB Configuration" >> .env.azure
echo "COSMOS_ENDPOINT=$COSMOS_ENDPOINT" >> .env.azure
echo "COSMOS_DB_ENDPOINT=$COSMOS_ENDPOINT" >> .env.azure

# Check for COSMOS_KEY or COSMOS_DB_KEY
COSMOS_KEY=""
if grep -q "COSMOS_KEY" "$ENV_FILE"; then
  COSMOS_KEY=$(grep "COSMOS_KEY" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_KEY in $ENV_FILE${NC}"
elif grep -q "COSMOS_DB_KEY" "$ENV_FILE"; then
  COSMOS_KEY=$(grep "COSMOS_DB_KEY" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_DB_KEY in $ENV_FILE${NC}"
else
  echo -e "${RED}No Cosmos DB key found in $ENV_FILE${NC}"
  echo -e "${YELLOW}Using placeholder value. Please update before deployment.${NC}"
  COSMOS_KEY="placeholder_cosmos_key"
fi

# Add standardized COSMOS KEY variables to .env.azure
echo "COSMOS_KEY=$COSMOS_KEY" >> .env.azure
echo "COSMOS_DB_KEY=$COSMOS_KEY" >> .env.azure

# Check for COSMOS_DATABASE or COSMOS_DB_DATABASE_ID
COSMOS_DATABASE=""
if grep -q "COSMOS_DATABASE" "$ENV_FILE"; then
  COSMOS_DATABASE=$(grep "COSMOS_DATABASE" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_DATABASE in $ENV_FILE${NC}"
elif grep -q "COSMOS_DB_DATABASE_ID" "$ENV_FILE"; then
  COSMOS_DATABASE=$(grep "COSMOS_DB_DATABASE_ID" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found COSMOS_DB_DATABASE_ID in $ENV_FILE${NC}"
else
  echo -e "${YELLOW}No Cosmos DB database name found in $ENV_FILE${NC}"
  echo -e "${YELLOW}Using default value 'thinkforward'.${NC}"
  COSMOS_DATABASE="thinkforward"
fi

# Add standardized COSMOS DATABASE variables to .env.azure
echo "COSMOS_DATABASE=$COSMOS_DATABASE" >> .env.azure
echo "COSMOS_DB_DATABASE_ID=$COSMOS_DATABASE" >> .env.azure
echo "" >> .env.azure

# Handle Azure AD variables
echo -e "${YELLOW}Standardizing Azure AD variables...${NC}"

# Check for Azure AD variables
if grep -q "AZURE_AD_CLIENT_ID" "$ENV_FILE"; then
  AZURE_AD_CLIENT_ID=$(grep "AZURE_AD_CLIENT_ID" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found AZURE_AD_CLIENT_ID in $ENV_FILE${NC}"
  echo "AZURE_AD_CLIENT_ID=$AZURE_AD_CLIENT_ID" >> .env.azure
fi

if grep -q "AZURE_AD_CLIENT_SECRET" "$ENV_FILE"; then
  AZURE_AD_CLIENT_SECRET=$(grep "AZURE_AD_CLIENT_SECRET" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found AZURE_AD_CLIENT_SECRET in $ENV_FILE${NC}"
  echo "AZURE_AD_CLIENT_SECRET=$AZURE_AD_CLIENT_SECRET" >> .env.azure
fi

if grep -q "AZURE_AD_TENANT_ID" "$ENV_FILE"; then
  AZURE_AD_TENANT_ID=$(grep "AZURE_AD_TENANT_ID" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found AZURE_AD_TENANT_ID in $ENV_FILE${NC}"
  echo "AZURE_AD_TENANT_ID=$AZURE_AD_TENANT_ID" >> .env.azure
fi

# Handle NextAuth variables
echo -e "${YELLOW}Standardizing NextAuth variables...${NC}"

if grep -q "NEXTAUTH_SECRET" "$ENV_FILE"; then
  NEXTAUTH_SECRET=$(grep "NEXTAUTH_SECRET" "$ENV_FILE" | cut -d '=' -f2-)
  echo -e "${GREEN}Found NEXTAUTH_SECRET in $ENV_FILE${NC}"
  echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.azure
else
  # Generate a new secret if not found
  NEXTAUTH_SECRET=$(openssl rand -hex 32)
  echo -e "${YELLOW}Generated new NEXTAUTH_SECRET${NC}"
  echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.azure
fi

# Add NODE_ENV and other required variables
echo "NODE_ENV=production" >> .env.azure

echo -e "${GREEN}Environment variables standardized in .env.azure${NC}"
echo -e "${BLUE}=== Review the .env.azure file before deploying ===${NC}"

# Instructions for Azure deployment
echo -e "${YELLOW}To deploy to Azure:${NC}"
echo -e "1. Review the .env.azure file to ensure all variables are correctly set"
echo -e "2. Use the automate-azure-setup.sh script to configure your Azure Web App"
echo -e "3. Update the GitHub Actions workflow to use these standardized variables"

exit 0